swagger: "2.0"
info:
  version: "0.0.1"
  title: Twitter-Task
# during dev, should point to your local machine
host: twit-task-api.herokuapp.com
# basePath prefixes all resource paths 
basePath: /
# 
schemes:
  # tip: remove http to make production-grade
  - http
  - https
# format of bodies a client can send (Content-Type)
consumes:
  - application/json
  - application/octet-stream
# format of the responses to the client (Accepts)
produces:
  - application/json
  - application/octet-stream
paths:
  /:
    x-swagger-router-controller: main
    get:
      description: Streams tweets from the twitter streaming api along with saving into the backend into the DB
      # used as the method name of the controller
      operationId: streamTweets  
      responses:
        "200":
          description: Success
          schema:
            # a pointer to a definition
            $ref: "#/definitions/Tweets"
        # responses may fall through to errors
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /api/tweets:
    x-swagger-router-controller: main
    get:
      description: Returns tweets saved into the DB
      # used as the method name of the controller
      operationId: getTweets
      parameters:
        - name: perPage
          in: query
          description: Page limit per request defaulted to 50
          required: false
          type: number
        - name: currentPage
          in: query
          description: currentPage for pagination, defaulted to 1
          required: false
          type: number  
      responses:
        "200":
          description: Success
          schema:
            # a pointer to a definition
            $ref: "#/definitions/Tweets"
        # responses may fall through to errors
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"         
  /swagger:
    x-swagger-pipe: swagger_raw
# complex objects have schema definitions
definitions:
  Tweets:
    type: array
    items: 
        $ref: "#/definitions/Tweet"
  Tweet:
    type: "object"
    properties:
      id_str: 
        type: "string"
      user: 
        type: "object"
      text: 
        type: "string"
      created_at: 
        type: "string"
      favorite_count: 
        type: "string"
      retweet_count: 
        type: "string"
      entities: 
        type: "object"
      
  ErrorResponse:
    required:
      - message
    properties:
      message:
        type: string
